const MESSAGES: Record<string, string> = {
  NOT_CONFIGURED: 'The app is not connected to a database yet.',
  NOT_SIGNED_IN: 'Please sign in first.',
  FORBIDDEN: "You don't have permission to do that.",
  NOT_FOUND: "That's no longer there: it may have been deleted. Reload the page.",
  INVALID_NAME: 'Names must be 1–60 characters.',
  INVALID_SETTINGS: 'Those season settings are not valid.',
  LEAGUE_EXISTS: 'That season already has a league with this name.',
  INVALID_CODE: 'Invite codes are 6–20 letters or digits.',
  CODE_TAKEN: 'That invite code already exists.',
  ATHLETE_EXISTS: 'An athlete with that name is already in this season.',
  ATHLETE_IN_USE: "This athlete has stats, bids or picks, so they weren't removed. Opt them out instead.",
  NO_PROFILE: 'Set your display name first.',
  INVALID_TEAM_NAME: 'Team names must be 1–40 characters.',
  INVALID_INVITE: 'That invite code is invalid, expired, or used up.',
  INVALID_INVITE_SETTINGS: 'Invite settings are not valid (max uses must be at least 1).',
  ALREADY_MEMBER: "You're already in this league.",
  TEAM_NAME_TAKEN: 'Another team in this league already has that name.',
  INVALID_ROLE: 'Unknown role.',
  LAST_ADMIN: "You can't remove the last admin.",
  INVALID_SESSION: 'That tally needs a date.',
  SESSION_VERIFIED: 'These stats are already verified. Ask a keeper to reopen them.',
  SESSION_LOCKED: 'These stats are locked. Only an admin correction can change them now.',
  SESSION_NOT_VERIFIED: "These stats aren't verified yet.",
  SESSION_NOT_EMPTY: "This tally already has saved taps, so it can't be deleted.",
  SESSION_NOT_LOCKED: 'Corrections are only for locked stats. Reopen the tally instead.',
  VERIFIER_TAPPED: 'You tallied this game, so another keeper has to verify it.',
  OWNS_ATHLETE: 'You own a player this affects, so someone else has to do this.',
  UNKNOWN_STAT: "That stat isn't tracked this season.",
  INVALID_TAPS: 'Some taps were malformed and were not saved.',
  INVALID_LINES: 'Those stat totals are not valid.',
  LINES_MISMATCH: "Those totals don't match the taps. Reload and try again.",
  NOT_YOUR_ATHLETE: 'You can only update your own attendance and injuries.',
  INVALID_STATUS: 'Attendance must be present or absent.',
  USER_ALREADY_LINKED: 'That account is already linked to another athlete this season.',
  INVALID_DATES: 'The end date must be on or after the start date.',
  STAGE_OVERLAP: 'Those dates overlap another tournament.',
  STAGE_EXISTS: 'A tournament with that name already exists this season.',
  LEAGUE_FULL: 'This league is full.',
  DONATIONS_DISABLED: 'Recording donations to the team is turned off for this season.',
  INVALID_AMOUNT: "That amount isn't valid.",
  NOTE_REQUIRED: 'Add a note saying why.',
  INVALID_NOTE: 'Notes must be 200 characters or fewer.',
  AUCTION_NOT_OPEN: "Bidding for this tournament hasn't opened yet.",
  BID_CLOSED: 'Bidding for this tournament has closed.',
  AUCTION_ALREADY_RUN: "This tournament's auction has already run.",
  AUCTION_NOT_CLOSED: 'Bidding is still open. Run the auction after it closes.',
  INVALID_CLOSE_TIME: 'Pick a closing time in the future.',
  INSUFFICIENT_CREDITS: 'Not enough credits for that bid.',
  SELF_OWNERSHIP: "You can't bid on yourself.",
  NOT_OPTED_IN: "That player isn't in this tournament's auction.",
  NOT_MEMBER: "That isn't your team.",
  PICK_LOCKED: 'That game has started, so its picks are locked.',
  NOT_NEXT_GAME: 'You can only pick for the next game.',
  GAMES_EXIST: 'This tournament is already open.',
  GAME_STARTED: 'Another keeper already started this game.',
  GAME_NOT_LIVE: "This game isn't being played right now: it's finished or hasn't started.",
  PREVIOUS_GAME_LIVE: 'Finish the game before this one first.',
  GAME_NOT_STARTED: "This game hasn't started, so there's nothing to undo.",
  NOT_LATEST_GAME: 'Undo the newest game first: only the latest played game can be undone.',
  PAIRINGS_INVALID: "Those pairings don't include every team exactly once. Reload and try again.",
  TOURNAMENT_STARTED: 'The tournament has started, so the bench is set. Use Swap in if an active player is injured.',
  TOURNAMENT_NOT_STARTED: "The tournament hasn't started yet. Change your bench instead.",
  BENCH_SIZE: "That's the wrong number of bench players.",
  NOT_ACTIVE: "That player isn't one of your active players.",
  NOT_ON_BENCH: "That player isn't on your bench.",
  NOT_INJURED: 'You can swap only for a player with a confirmed injury.',
  SWAP_USED: "You've already used your bench swap this tournament.",
  NOT_ON_ROSTER: "That player isn't on your roster this tournament.",
  STANDINGS_MISSING: "The standings didn't include every team. Reload and try again.",
  NOT_ENOUGH_ATHLETES: '{detail} has more roster spots than healthy opted-in players. Opt in more players or lower the roster size.',
};

/** `{detail}` in a message is replaced by the error's detail (Postgres DETAIL), e.g. a league name. */
export function errorMessage(err: unknown): string {
  const e = typeof err === 'object' && err !== null ? (err as { message?: unknown; details?: unknown; detail?: unknown }) : {};
  const raw = 'message' in e ? String(e.message) : String(err);
  const detail = String(e.details ?? e.detail ?? 'A league');
  return MESSAGES[raw.trim()]?.replace('{detail}', detail)
    ?? `Something went wrong (${raw}). Try again, and tell an admin if it keeps happening.`;
}
